title: Chiyu Max Jiang
email: maxjiang93@gmail.com
description: Research Scientist, Waymo Research. 3D Deep Learning | Computer Vision | Self-driving Cars. # this means to ignore newlines until "baseurl:"
keywords: 3D Deep Learning, 3D Computer Vision, Scientific Computing
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: "Chiyu 'Max' Jiang (蒋驰宇)" # add your name
author-pic: max_profile_pic_sq.JPG
about-author: Research Scientist, Waymo Research </br> 3D Deep Learning | Computer Vision | Self-driving Cars

# Contact links
email: maxjiang93@gmail.com # Add your Email address
phone: (607) 379-4895 # Add your Phone number
website: www.maxjiang.ml # Add your website, do not add http://
linkedin: maxcjiang # Add your Linkedin handle
github: maxjiang93 # Add your Github handle

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: www-maxjiang-ml # Add your discus identifier

# Tracker
analytics: UA-107351529-1 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  
version: v1.2.0

include: [_pages, _proj]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "Gemfile", "Gemfile.lock"]
future: true
