title: "Max Jiang's Blog and Webpage"
email: chiyu.jiang@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog and webpage to blog some of my research projects and other fun stuff.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "maxjiang93.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: "Max" Chiyu Jiang # add your name
author-pic: max-face.jpg
about-author: "My name is Max Jiang. I’m a PhD student in UC Berkeley. My research interest is in Deep Learning and AI, and its applications in fluid related physics."

# Contact links
email: chiyu.jiang@berkeley.edu # Add your Email address
phone: (607) 379-4895 # Add your Phone number
website: cfd.me.berkeley.edu/people/chiyu-max-jiang/ # Add your website, do not add http://
linkedin: maxcjiang # Add your Linkedin handle
github: maxjiang93 # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle
 
# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  
version: v1.2.0

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "Gemfile", "Gemfile.lock"]
