title: Chiyu Max Jiang
email: chiyu.jiang@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Chiyu 'Max' Jiang
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: "Chiyu 'Max' Jiang (蒋驰宇)" # add your name
author-pic: max_profile_pic_sq.JPG
about-author: Ph.D student at UC Berkeley. </br> Deep Learning methods for 3D Geometries and Physical Systems.

# Contact links
email: chiyu.jiang@berkeley.edu # Add your Email address
phone: (607) 379-4895 # Add your Phone number
website: cfd.me.berkeley.edu/people/chiyu-max-jiang/ # Add your website, do not add http://
linkedin: maxcjiang # Add your Linkedin handle
github: maxjiang93 # Add your Github handle

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: www-maxjiang-ml # Add your discus identifier

# Tracker
analytics: UA-107351529-1 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  
version: v1.2.0

include: [_pages, _proj]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "Gemfile", "Gemfile.lock"]
